src/Web/BeHealthy.Web/Areas/Fitness/Controllers/ExercisesController.cs
namespace BeHealthy.Web.Areas.Fitness.Controllers
{
    using System.Threading.Tasks;

    using BeHealthy.Data.Models;
    using BeHealthy.Services.Data.Exercises;
    using BeHealthy.Services.Data.ExerciseSteps;
    using BeHealthy.Services.Data.Ratings;
    using BeHealthy.Web.Dtos.Fitness.Exercises.InputModels;
    using BeHealthy.Web.Dtos.Fitness.Exercises.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using static BeHealthy.Common.GlobalConstants;
    using static BeHealthy.Common.Messages;

    [Authorize]
    [Area("Fitness")]
    public class ExercisesController : Controller
    {
        private readonly IExercisesService exercisesService;
        private readonly IRatingsService reviewsService;
        private readonly UserManager<ApplicationUser> userManager;

        public ExercisesController(
            IExercisesService exerciseService,
            IRatingsService reviewService,
            UserManager<ApplicationUser> userManager)
        {
            this.exercisesService = exerciseService;
            this.reviewsService = reviewService;
            this.userManager = userManager;
        }

        [Route("/{area}/{controller}/{page:int:min(1)=1}")]
        public async Task<IActionResult> Browse(int page)
        {
            var lastPage = await this.exercisesService.GetPublishedExercisesPagesCountAsync(ElementsPerPage);

            if (lastPage < page && lastPage != 0)
            {
                return this.RedirectToAction(nameof(this.Browse), new { page = 1 });
            }

            var viewModel = await this.exercisesService.GetPublishedExercisesAsync<ExerciseListItemViewModel, System.DateTime?>(page, ElementsPerPage, x => x.ModifiedOn);

            this.ViewData[CurrentPageKey] = page;
            this.ViewData[LastPageKey] = lastPage;

            return this.View(viewModel);
        }

        [Route("/{area}/{controller}/{tag:regex(^[[a-z\\-]]+$)}/{page:int:min(1)=1}")]
        public async Task<IActionResult> AllWithTag(int page, string tag)
        {
            var lastPage = await this.exercisesService.GetPublishedExercisesWithTagPagesCountAsync(ElementsPerPage, tag);

            if (lastPage < page && lastPage != 0)
            {
                return this.RedirectToAction(nameof(this.AllWithTag), new { page = 1, tag });
            }

            var viewModel = await this.exercisesService.GetPublishedExercisesWithTagAsync<ExerciseListItemViewModel, System.DateTime?>(page, ElementsPerPage, tag, x => x.ModifiedOn);

            this.ViewData[CurrentPageKey] = page;
            this.ViewData[TagKey] = tag;
            this.ViewData[LastPageKey] = lastPage;

            return this.View(viewModel);
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ExerciseInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            string creatorId = this.userManager.GetUserId(this.User);

            string exerciseId = await this.exercisesService.CreateAsync(inputModel, creatorId);

            this.TempData[InfoMessageKey] = CreatedSuccessfully;

            return this.RedirectToAction(nameof(this.Details), new { exerciseId });
        }

        public async Task<IActionResult> Details(string exerciseId)
        {
            var viewModel = await this.exercisesService.GetExerciseAsync<ExerciseViewModel>(exerciseId);

            if (viewModel == null)
            {
                this.TempData[ErrorMessageKey] = InvalidExercise;
                return this.RedirectToAction(nameof(this.Browse));
            }

            var accessor = await this.userManager.GetUserAsync(this.User);
            bool isAccessorCreator = await this.exercisesService.IsUserExerciseCreatorAsync(exerciseId, accessor.Id);

            // If user is not the creator of the exercise when it's not published, he/she cannot access that page.
            if (!viewModel.IsPublished && !isAccessorCreator && !this.User.IsInRole(AdministratorRoleName))
            {
                this.TempData[ErrorMessageKey] = InvalidExercise;
                return this.RedirectToAction(nameof(this.Browse));
            }

            viewModel.IsAcessorCreator = isAccessorCreator;
            viewModel.ExerciseReviewUserRating = await this.reviewsService.GetExerciseReviewRatingAsync(exerciseId, accessor.Id);

            return this.View(viewModel);
        }

        public async Task<IActionResult> ChangePublishState(string exerciseId)
        {
            var accessorId = this.userManager.GetUserId(this.User);

            if (!await this.exercisesService.IsUserExerciseCreatorAsync(exerciseId, accessorId))
            {
                this.TempData[ErrorMessageKey] = InvalidExercise;
                return this.RedirectToAction(nameof(this.Browse));
            }

            await this.exercisesService.ChangePublishState(exerciseId);

            this.TempData[InfoMessageKey] = ChangesSavedSuccessfully;

            return this.RedirectToAction(nameof(this.Details), new { exerciseId });
        }

        public async Task<IActionResult> Delete(string exerciseId)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.exercisesService.IsUserExerciseCreatorAsync(exerciseId, userId) && !this.User.IsInRole(AdministratorRoleName))
            {
                this.TempData[ErrorMessageKey] = InvalidExercise;
                return this.RedirectToAction(nameof(this.Browse));
            }

            await this.exercisesService.DeleteExerciseAsync(exerciseId);

            this.TempData[InfoMessageKey] = DeletedSuccessfully;

            return this.RedirectToAction(nameof(this.Browse));
        }
    }
}

src/Web/BeHealthy.Web/Areas/Fitness/Controllers/WorkoutsController.cs
namespace BeHealthy.Web.Areas.Fitness.Controllers
{
    using System.Threading.Tasks;

    using BeHealthy.Data.Models;
    using BeHealthy.Services.Data.Exercises;
    using BeHealthy.Services.Data.WorkoutExercises;
    using BeHealthy.Services.Data.Workouts;
    using BeHealthy.Web.Dtos.Fitness.Workouts.InputModels;
    using BeHealthy.Web.Dtos.Fitness.Workouts.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using static BeHealthy.Common.GlobalConstants;
    using static BeHealthy.Common.Messages;

    [Authorize]
    [Area("Fitness")]
    public class WorkoutsController : Controller
    {
        private readonly IWorkoutsService workoutsService;
        private readonly IExercisesService exercisesService;
        private readonly IWorkoutExercisesService workoutExercisesService;
        private readonly UserManager<ApplicationUser> userManager;

        public WorkoutsController(
            IWorkoutsService workoutService,
            IExercisesService exerciseService,
            IWorkoutExercisesService workoutExerciseService,
            UserManager<ApplicationUser> userManager)
        {
            this.workoutsService = workoutService;
            this.exercisesService = exerciseService;
            this.workoutExercisesService = workoutExerciseService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Schedule()
        {
            var userId = this.userManager.GetUserId(this.User);

            var viewModel = await this.workoutsService.GetAllUserWorkoutsAsync<WorkoutViewModel>(userId);

            return this.View(viewModel);
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(WorkoutInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            string creatorId = this.userManager.GetUserId(this.User);

            string workoutId = await this.workoutsService.CreateAsync(inputModel, creatorId);

            return this.RedirectToAction(nameof(this.Details), new { workoutId });
        }

        public async Task<IActionResult> Edit(string workoutId)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.workoutsService.IsUserWorkoutCreatorAsync(workoutId, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidWorkout;
                return this.RedirectToAction(nameof(this.Schedule));
            }

            var viewModel = await this.workoutsService.GetWorkoutAsync<WorkoutEditInputModel>(workoutId);

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(WorkoutEditInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            var userId = this.userManager.GetUserId(this.User);

            if (!await this.workoutsService.IsUserWorkoutCreatorAsync(inputModel.Id, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidWorkout;
                return this.RedirectToAction(nameof(this.Schedule));
            }

            await this.workoutsService.EditAsync(inputModel);

            return this.RedirectToAction(nameof(this.Details), new { workoutId = inputModel.Id });
        }

        public async Task<IActionResult> Delete(string workoutId)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.workoutsService.IsUserWorkoutCreatorAsync(workoutId, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidWorkout;
                return this.RedirectToAction(nameof(this.Schedule));
            }

            await this.workoutsService.DeleteWorkoutAsync(workoutId);

            return this.RedirectToAction(nameof(this.Schedule));
        }

        public async Task<IActionResult> Details(string workoutId)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.workoutsService.IsUserWorkoutCreatorAsync(workoutId, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidWorkout;
                return this.RedirectToAction(nameof(this.Schedule));
            }

            var viewModel = await this.workoutsService.GetWorkoutAsync<WorkoutDetailsViewModel>(workoutId);

            return this.View(viewModel);
        }

        public async Task<IActionResult> AddExercise(string exerciseId)
        {
            var userId = this.userManager.GetUserId(this.User);

            var viewModel = new WorkoutExerciseCreateInputModel
            {
                ExerciseId = exerciseId,
            };

            this.ViewData["WorkoutSelectListItems"] = await this.workoutsService.GetAllUserWorkoutsAsync<WorkoutSelectListItemViewModel>(userId);

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddExercise(WorkoutExerciseCreateInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            if (!await this.exercisesService.IsExercisePublishedAsync(inputModel.ExerciseId))
            {
                this.TempData[ErrorMessageKey] = InvalidExercise;
                return this.RedirectToAction("Browse", "Exercises");
            }

            var userId = this.userManager.GetUserId(this.User);

            if (await this.workoutExercisesService.WorkoutExerciseExistsAsync(inputModel.WorkoutId, inputModel.ExerciseId))
            {
                this.TempData[ErrorMessageKey] = "Exercise is already in workout.";
                return this.RedirectToAction("Browse", "Exercises");
            }

            if (!await this.workoutsService.IsUserWorkoutCreatorAsync(inputModel.WorkoutId, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidWorkout;
                return this.RedirectToAction("Browse", "Exercises");
            }

            await this.workoutExercisesService.AddWorkoutExerciseAsync(inputModel);
            this.TempData[InfoMessageKey] = "Exercise added.";

            return this.RedirectToAction("Browse", "Exercises");
        }

        public async Task<IActionResult> RemoveExercise(string workoutId, string exerciseId)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.workoutsService.IsUserWorkoutCreatorAsync(workoutId, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidWorkout;
                return this.RedirectToAction(nameof(this.Schedule));
            }

            var success = await this.workoutExercisesService.DeleteWorkoutExerciseAsync(workoutId, exerciseId);

            if (!success)
            {
                this.TempData[ErrorMessageKey] = ChangesUnsuccessful;
            }
            else
            {
                this.TempData[InfoMessageKey] = "Exercise removed.";
            }

            return this.RedirectToAction(nameof(this.Details), new { workoutId });
        }
    }
}

src/Web/BeHealthy.Web/Controllers/UsersController.cs
namespace BeHealthy.Web.Controllers
{
    using System.Threading.Tasks;

    using BeHealthy.Services.Data.Users;
    using BeHealthy.Web.Dtos.Users.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using static BeHealthy.Common.GlobalConstants;

    [Authorize]
    public class UsersController : Controller
    {
        private readonly IUsersService usersService;

        public UsersController(IUsersService userService)
        {
            this.usersService = userService;
        }

        [Route("{controller}/{username:required}")]
        public async Task<IActionResult> Details(string username)
        {
            if (!await this.usersService.UserExistsAsync(username))
            {
                this.TempData[ErrorMessageKey] = $"User {username} does not exist.";
                return this.RedirectToAction("Index", "Home");
            }

            var viewModel = await this.usersService.GetUserDetailsAsync<UserDetailsViewModel>(username);

            return this.View(viewModel);
        }
    }
}

src/Web/BeHealthy.Web/ViewComponents/UnpublishedExercisesViewComponent.cs
namespace BeHealthy.Web.ViewComponents
{
    using System.Threading.Tasks;

    using BeHealthy.Data.Models;
    using BeHealthy.Services.Data.Exercises;
    using BeHealthy.Web.Dtos.Fitness.Exercises.ViewModels;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [ViewComponent(Name = "UnpublishedExercises")]
    public class UnpublishedExercisesViewComponent : ViewComponent
    {
        private readonly IExercisesService exercisesService;
        private readonly UserManager<ApplicationUser> userManager;

        public UnpublishedExercisesViewComponent(IExercisesService exerciseService, UserManager<ApplicationUser> userManager)
        {
            this.exercisesService = exerciseService;
            this.userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userId = this.userManager.GetUserId(this.UserClaimsPrincipal);

            var viewModel = await this.exercisesService.GetUnpublishedExercisesAsync<UnpublishedExerciseViewModel>(userId);

            return this.View(viewModel);
        }
    }
}

src/Web/BeHealthy.Web/Areas/Fitness/Views/Exercises/AllWithTag.cshtml
@model IEnumerable<ExerciseListItemViewModel>

@{
    ViewData["Title"] = "Browse";
}

<h1>Results for tag: @this.ViewData["Tag"]</h1>
<hr />
@if (!Model.Any())
{
    <h2>No results found. <a asp-area="Fitness" asp-controller="Exercises" asp-action="Browse" class="btn btn-primary">To Browse</a></h2>
}
else
{
    <div class="row">
        <div class="col-md-10">
            @foreach (var exercise in Model)
            {
                <div class="card my-2">
                    <h5 class="card-header">@exercise.Name</h5>
                    <div class="card-body">
                        <h5 class="card-title">Creator: <a asp-area="" asp-controller="Users" asp-action="Details" asp-route-username="@exercise.CreatorUserName" class="text-dark">@exercise.CreatorUserName</a></h5>
                        <h6 class="card-title">Rating: @exercise.Rating.ToString("f2") <i class="fa fa-star"></i></h6>
                        <p class="card-text">@exercise.Description</p>
                        <a asp-area="Fitness" asp-controller="Exercises" asp-action="Details" asp-route-exerciseId="@exercise.Id" class="btn btn-primary">Details</a>
                    </div>
                </div>
            }
        </div>
        <div class="col-md-2">
            <strong>You want to share an exercise idea? <a class="btn btn-primary" asp-area="Fitness" asp-controller="Exercises" asp-action="Create">Click here!</a></strong>
            @await Component.InvokeAsync("UnpublishedExercises")
        </div>
    </div>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-md-center">
            @if ((int)this.ViewData["Page"] - 1 >= 1)
            {
                <li class="page-item"><a asp-area="Fitness" asp-controller="Exercises" asp-action="AllWithTag" asp-route-page="@((int)this.ViewData["Page"] - 1)" asp-route-tag="@this.ViewData["Tag"]" class="page-link">Previous</a></li>
            }
            else
            {
                <li class="page-item disabled"><a class="page-link" disabled>Previous</a></li>
            }
            @for (int p = 1; p <= (int)this.ViewData["LastPage"]; p++)
            {
                @if (p == (int)this.ViewData["Page"])
                {
                    <li class="page-item active"><a asp-area="Fitness" asp-controller="Exercises" asp-action="AllWithTag" asp-route-page="@p" class="page-link" asp-route-tag="@this.ViewData["Tag"]">@p</a></li>
                }
                else
                {
                    <li class="page-item"><a asp-area="Fitness" asp-controller="Exercises" asp-action="AllWithTag" asp-route-page="@p" class="page-link" asp-route-tag="@this.ViewData["Tag"]">@p</a></li>
                }
            }
            @if ((int)this.ViewData["Page"] + 1 <= (int)this.ViewData["LastPage"])
            {
                <li class="page-item"><a asp-area="Fitness" asp-controller="Exercises" asp-action="AllWithTag" asp-route-page="@((int)this.ViewData["Page"] + 1)" asp-route-tag="@this.ViewData["Tag"]" class="page-link">Next</a></li>
            }
            else
            {
                <li class="page-item disabled"><a class="page-link">Next</a></li>
            }
        </ul>
    </nav>
}

src/Web/BeHealthy.Web/Areas/Fitness/Views/Exercises/Browse.cshtml
@model IEnumerable<ExerciseListItemViewModel>

@{
    ViewData["Title"] = "Browse";
}

<h1>Browse</h1>
<hr />
<div class="row">
    <div class="col-md-10">
        @foreach (var exercise in Model)
        {
            <div class="card my-2">
                <h5 class="card-header">@exercise.Name</h5>
                <div class="card-body">
                    <h5 class="card-title">Creator: <a asp-area="" asp-controller="Users" asp-action="Details" asp-route-username="@exercise.CreatorUserName" class="text-dark">@exercise.CreatorUserName</a></h5>
                    <h6 class="card-title">Rating: @exercise.Rating.ToString("f2") <i class="fa fa-star"></i></h6>
                    <p class="card-text">@exercise.Description</p>
                    <a asp-area="Fitness" asp-controller="Exercises" asp-action="Details" asp-route-exerciseId="@exercise.Id" class="btn btn-primary">Details</a>
                </div>
            </div>
        }
    </div>
    <div class="col-md-2">
        <strong>You want to share an exercise idea? <a class="btn btn-primary" asp-area="Fitness" asp-controller="Exercises" asp-action="Create">Click here!</a></strong>
        @await Component.InvokeAsync("UnpublishedExercises")
    </div>
</div>

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-md-center">
        @if ((int)this.ViewData["Page"] - 1 >= 1)
        {
            <li class="page-item"><a asp-area="Fitness" asp-controller="Exercises" asp-action="Browse" asp-route-page="@((int)this.ViewData["Page"] - 1)" class="page-link">Previous</a></li>
        }
        else
        {
            <li class="page-item disabled"><a class="page-link" disabled>Previous</a></li>
        }
        @for (int p = 1; p <= (int)this.ViewData["LastPage"]; p++)
        {
            @if (p == (int)this.ViewData["Page"])
            {
                <li class="page-item active"><a asp-area="Fitness" asp-controller="Exercises" asp-action="Browse" asp-route-page="@p" class="page-link">@p</a></li>
            }
            else
            {
                <li class="page-item"><a asp-area="Fitness" asp-controller="Exercises" asp-action="Browse" asp-route-page="@p" class="page-link">@p</a></li>
            }
        }
        @if ((int)this.ViewData["Page"] + 1 <= (int)this.ViewData["LastPage"])
        {
            <li class="page-item"><a asp-area="Fitness" asp-controller="Exercises" asp-action="Browse" asp-route-page="@((int)this.ViewData["Page"] + 1)" class="page-link">Next</a></li>
        }
        else
        {
            <li class="page-item disabled"><a class="page-link">Next</a></li>
        }
    </ul>
</nav>

src/Web/BeHealthy.Web/Areas/Fitness/Views/Exercises/Create.cshtml
@model BeHealthy.Web.Dtos.Fitness.Exercises.InputModels.ExerciseInputModel

@{
    ViewData["Title"] = "Create";
}

<form asp-area="Fitness" asp-controller="Exercises" asp-action="Create" method="post">
    <h1>Create an exercise</h1>
    <hr />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <a class="btn btn-danger float-left" asp-area="Fitness" asp-controller="Exercises" asp-action="Browse">Cancel</a>
    <button type="submit" class="btn btn-success float-right">Create</button>
</form>