src/Web/BeHealthy.Web/Areas/Fitness/Controllers/WorkoutsController.cs
namespace BeHealthy.Web.Areas.Fitness.Controllers
{
    using System.Threading.Tasks;

    using BeHealthy.Data.Models;
    using BeHealthy.Services.Data.Exercises;
    using BeHealthy.Services.Data.WorkoutExercises;
    using BeHealthy.Services.Data.Workouts;
    using BeHealthy.Web.Dtos.Fitness.Workouts.InputModels;
    using BeHealthy.Web.Dtos.Fitness.Workouts.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using static BeHealthy.Common.GlobalConstants;
    using static BeHealthy.Common.Messages;

    [Authorize]
    [Area("Fitness")]
    public class WorkoutsController : Controller
    {
        private readonly IWorkoutsService workoutsService;
        private readonly IExercisesService exercisesService;
        private readonly IWorkoutExercisesService workoutExercisesService;
        private readonly UserManager<ApplicationUser> userManager;

        public WorkoutsController(
            IWorkoutsService workoutService,
            IExercisesService exerciseService,
            IWorkoutExercisesService workoutExerciseService,
            UserManager<ApplicationUser> userManager)
        {
            this.workoutsService = workoutService;
            this.exercisesService = exerciseService;
            this.workoutExercisesService = workoutExerciseService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Schedule()
        {
            var userId = this.userManager.GetUserId(this.User);

            var viewModel = await this.workoutsService.GetAllUserWorkoutsAsync<WorkoutViewModel>(userId);

            return this.View(viewModel);
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(WorkoutInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            string creatorId = this.userManager.GetUserId(this.User);

            string workoutId = await this.workoutsService.CreateAsync(inputModel, creatorId);

            return this.RedirectToAction(nameof(this.Details), new { workoutId });
        }

        public async Task<IActionResult> Edit(string workoutId)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.workoutsService.IsUserWorkoutCreatorAsync(workoutId, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidWorkout;
                return this.RedirectToAction(nameof(this.Schedule));
            }

            var viewModel = await this.workoutsService.GetWorkoutAsync<WorkoutEditInputModel>(workoutId);

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(WorkoutEditInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            var userId = this.userManager.GetUserId(this.User);

            if (!await this.workoutsService.IsUserWorkoutCreatorAsync(inputModel.Id, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidWorkout;
                return this.RedirectToAction(nameof(this.Schedule));
            }

            await this.workoutsService.EditAsync(inputModel);

            return this.RedirectToAction(nameof(this.Details), new { workoutId = inputModel.Id });
        }

        public async Task<IActionResult> Delete(string workoutId)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.workoutsService.IsUserWorkoutCreatorAsync(workoutId, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidWorkout;
                return this.RedirectToAction(nameof(this.Schedule));
            }

            await this.workoutsService.DeleteWorkoutAsync(workoutId);

            return this.RedirectToAction(nameof(this.Schedule));
        }

        public async Task<IActionResult> Details(string workoutId)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.workoutsService.IsUserWorkoutCreatorAsync(workoutId, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidWorkout;
                return this.RedirectToAction(nameof(this.Schedule));
            }

            var viewModel = await this.workoutsService.GetWorkoutAsync<WorkoutDetailsViewModel>(workoutId);

            return this.View(viewModel);
        }

        public async Task<IActionResult> AddExercise(string exerciseId)
        {
            var userId = this.userManager.GetUserId(this.User);

            var viewModel = new WorkoutExerciseCreateInputModel
            {
                ExerciseId = exerciseId,
            };

            this.ViewData["WorkoutSelectListItems"] = await this.workoutsService.GetAllUserWorkoutsAsync<WorkoutSelectListItemViewModel>(userId);

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddExercise(WorkoutExerciseCreateInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            if (!await this.exercisesService.IsExercisePublishedAsync(inputModel.ExerciseId))
            {
                this.TempData[ErrorMessageKey] = InvalidExercise;
                return this.RedirectToAction("Browse", "Exercises");
            }

            var userId = this.userManager.GetUserId(this.User);

            if (await this.workoutExercisesService.WorkoutExerciseExistsAsync(inputModel.WorkoutId, inputModel.ExerciseId))
            {
                this.TempData[ErrorMessageKey] = "Exercise is already in workout.";
                return this.RedirectToAction("Browse", "Exercises");
            }

            if (!await this.workoutsService.IsUserWorkoutCreatorAsync(inputModel.WorkoutId, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidWorkout;
                return this.RedirectToAction("Browse", "Exercises");
            }

            await this.workoutExercisesService.AddWorkoutExerciseAsync(inputModel);
            this.TempData[InfoMessageKey] = "Exercise added.";

            return this.RedirectToAction("Browse", "Exercises");
        }

        public async Task<IActionResult> RemoveExercise(string workoutId, string exerciseId)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.workoutsService.IsUserWorkoutCreatorAsync(workoutId, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidWorkout;
                return this.RedirectToAction(nameof(this.Schedule));
            }

            var success = await this.workoutExercisesService.DeleteWorkoutExerciseAsync(workoutId, exerciseId);

            if (!success)
            {
                this.TempData[ErrorMessageKey] = ChangesUnsuccessful;
            }
            else
            {
                this.TempData[InfoMessageKey] = "Exercise removed.";
            }

            return this.RedirectToAction(nameof(this.Details), new { workoutId });
        }
    }
}

src/Web/BeHealthy.Web/Controllers/UsersController.cs
namespace BeHealthy.Web.Controllers
{
    using System.Threading.Tasks;

    using BeHealthy.Services.Data.Users;
    using BeHealthy.Web.Dtos.Users.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using static BeHealthy.Common.GlobalConstants;

    [Authorize]
    public class UsersController : Controller
    {
        private readonly IUsersService usersService;

        public UsersController(IUsersService userService)
        {
            this.usersService = userService;
        }

        [Route("{controller}/{username:required}")]
        public async Task<IActionResult> Details(string username)
        {
            if (!await this.usersService.UserExistsAsync(username))
            {
                this.TempData[ErrorMessageKey] = $"User {username} does not exist.";
                return this.RedirectToAction("Index", "Home");
            }

            var viewModel = await this.usersService.GetUserDetailsAsync<UserDetailsViewModel>(username);

            return this.View(viewModel);
        }
    }
}

src/Web/BeHealthy.Web/Views/Shared/_Layout.cshtml
@using BeHealthy.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <environment names="Development">
        <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <partial name="_NavigationLoggedInPartial" />
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />

        <main role="main" class="pb-3">
            <partial name="_MessagePartial" />
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @this.RenderSection("Scripts", required: false)
</body>
</html>

src/Web/BeHealthy.Web/Views/Shared/_MessagePartial.cshtml
@using BeHealthy.Common

@if (this.TempData[GlobalConstants.ErrorMessageKey] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>@this.TempData[GlobalConstants.ErrorMessageKey]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
else if (this.TempData[GlobalConstants.InfoMessageKey] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>@this.TempData[GlobalConstants.InfoMessageKey]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

src/Web/BeHealthy.Web/Views/Shared/_NavigationLoggedInPartial.cshtml
@if (this.User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Fitness" asp-controller="Exercises" asp-action="Browse">Exercises</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Fitness" asp-controller="Workouts" asp-action="Schedule">Workouts</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Details" asp-route-username="@this.User.Identity.Name">My profile</a>
    </li>
}