src/Web/BeHealthy.Web/Areas/Fitness/Controllers/ExerciseStepsController.cs
namespace BeHealthy.Web.Areas.Fitness.Controllers
{
    using System;
    using System.Threading.Tasks;

    using BeHealthy.Data.Models;
    using BeHealthy.Services.Cloudinary;
    using BeHealthy.Services.Data.Exercises;
    using BeHealthy.Services.Data.ExerciseSteps;
    using BeHealthy.Web.Dtos.Fitness.ExerciseSteps.InputModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using static BeHealthy.Common.GlobalConstants;
    using static BeHealthy.Common.Messages;

    [Authorize]
    [Area("Fitness")]
    public class ExerciseStepsController : Controller
    {
        private readonly IExerciseStepsService exerciseStepsService;
        private readonly IExercisesService exercisesService;
        private readonly ICloudinaryService cloudinaryService;
        private readonly UserManager<ApplicationUser> userManager;

        public ExerciseStepsController(
            IExerciseStepsService exerciseStepService,
            IExercisesService exerciseService,
            ICloudinaryService cloudinaryService,
            UserManager<ApplicationUser> userManager)
        {
            this.exerciseStepsService = exerciseStepService;
            this.exercisesService = exerciseService;
            this.cloudinaryService = cloudinaryService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Create(string exerciseId)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.exercisesService.IsUserExerciseCreatorAsync(exerciseId, userId))
            {
                this.TempData[ErrorMessageKey] = InvalidExercise;
                return this.RedirectToAction("Browse", "Exercises");
            }

            if (await this.exerciseStepsService.GetExerciseStepsCountAsync(exerciseId) > MaxExerciseStepsCount)
            {
                this.TempData[ErrorMessageKey] = string.Format(ExerciseStepMaxLimit, MaxExerciseStepsCount);
                return this.RedirectToAction("Details", "Exercises", new { exerciseId });
            }

            var viewModel = new ExerciseStepCreateInputModel
            {
                ExerciseId = exerciseId,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ExerciseStepCreateInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            if (!await this.exercisesService.IsUserExerciseCreatorAsync(inputModel.ExerciseId, user.Id))
            {
                this.TempData[ErrorMessageKey] = InvalidExercise;
                return this.RedirectToAction("Browse", "Exercises");
            }

            if (await this.exerciseStepsService.GetExerciseStepsCountAsync(inputModel.ExerciseId) > MaxExerciseStepsCount)
            {
                this.TempData[ErrorMessageKey] = string.Format(ExerciseStepMaxLimit, MaxExerciseStepsCount);
                return this.RedirectToAction("Details", "Exercises", new { inputModel.ExerciseId });
            }

            var imageUrl = await this.cloudinaryService.UploadImageAsync($"{Guid.NewGuid()}_{user.UserName}", user.UserName, inputModel.ImageUpload);

            await this.exerciseStepsService.CreateExerciseStepAsync(inputModel, imageUrl);

            this.TempData[InfoMessageKey] = CreatedSuccessfully;

            return this.RedirectToAction("Details", "Exercises", new { inputModel.ExerciseId });
        }

        public async Task<IActionResult> Edit(int exerciseStepId)
        {
            var exerciseId = await this.exercisesService.GetExerciseIdByStepIdAsync(exerciseStepId);

            var userId = this.userManager.GetUserId(this.User);

            if (!await this.exercisesService.IsUserExerciseCreatorAsync(exerciseId, userId) && !this.User.IsInRole(AdministratorRoleName))
            {
                this.TempData[ErrorMessageKey] = InvalidExerciseStep;
                return this.RedirectToAction("Browse", "Exercises");
            }

            var viewModel = await this.exerciseStepsService.GetExerciseStepAsync<ExerciseStepEditInputModel>(exerciseStepId);

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ExerciseStepEditInputModel exerciseStepEditInputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(exerciseStepEditInputModel);
            }

            var exerciseId = await this.exercisesService.GetExerciseIdByStepIdAsync(exerciseStepEditInputModel.Id);

            var user = await this.userManager.GetUserAsync(this.User);

            if (!await this.exercisesService.IsUserExerciseCreatorAsync(exerciseId, user.Id) && !this.User.IsInRole(AdministratorRoleName))
            {
                this.TempData[ErrorMessageKey] = InvalidExerciseStep;
                return this.RedirectToAction("Browse", "Exercises");
            }

            string newImageUrl = string.Empty;

            if (exerciseStepEditInputModel.ImageUpload != null)
            {
                newImageUrl = await this.cloudinaryService.UploadImageAsync($"{Guid.NewGuid()}_{user.UserName}", user.UserName, exerciseStepEditInputModel.ImageUpload);
            }

            await this.exerciseStepsService.UpdateExerciseStepAsync(exerciseStepEditInputModel, newImageUrl);

            this.TempData[InfoMessageKey] = ChangesSavedSuccessfully;

            return this.RedirectToAction("Details", "Exercises", new { exerciseId });
        }

        public async Task<IActionResult> Delete(int exerciseStepId)
        {
            var exerciseId = await this.exercisesService.GetExerciseIdByStepIdAsync(exerciseStepId);

            var userId = this.userManager.GetUserId(this.User);

            if (!await this.exercisesService.IsUserExerciseCreatorAsync(exerciseId, userId) && !this.User.IsInRole(AdministratorRoleName))
            {
                this.TempData[ErrorMessageKey] = InvalidExerciseStep;
                return this.RedirectToAction("Browse", "Exercises");
            }

            await this.exerciseStepsService.DeleteExerciseStepAsync(exerciseStepId);

            this.TempData[InfoMessageKey] = DeletedSuccessfully;

            return this.RedirectToAction("Details", "Exercises", new { exerciseId });
        }
    }
}

src/Web/BeHealthy.Web/Areas/Fitness/Views/ExerciseSteps/Create.cshtml
@model BeHealthy.Web.Dtos.Fitness.ExerciseSteps.InputModels.ExerciseStepCreateInputModel

@{
    ViewData["Title"] = "Create";
}

<form asp-area="Fitness" asp-controller="ExerciseSteps" asp-action="Create" method="post" enctype="multipart/form-data">
    <h1>Create an Exercise Step</h1>
    <hr />
    <div class="form-group">
        <label asp-for="Heading"></label>
        <input asp-for="Heading" class="form-control" />
        <span asp-validation-for="Heading" class="text-danger"></span>
    </div>
    <p>Image</p>
    <div class="custom-file">
        <input asp-for="ImageUpload" class="custom-file-input">
        <label asp-for="ImageUpload" class="custom-file-label">Choose image...</label>
        <span asp-validation-for="ImageUpload" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <input asp-for="ExerciseId" hidden>

    <a class="btn btn-danger float-left" asp-area="Fitness" asp-controller="Exercises" asp-action="Details" asp-route-exerciseId="@Model.ExerciseId">Cancel</a>
    <button type="submit" class="btn btn-success float-right">Create</button>
</form>

@section Scripts{
    <script type="text/javascript">changeFileInputLabel();</script>
}

src/Web/BeHealthy.Web/Areas/Fitness/Views/ExerciseSteps/Edit.cshtml
@model BeHealthy.Web.Dtos.Fitness.ExerciseSteps.InputModels.ExerciseStepEditInputModel

@{
    ViewData["Title"] = "Edit";
}

<form asp-area="Fitness" asp-controller="ExerciseSteps" asp-action="Edit" method="post" enctype="multipart/form-data">
    <h1>Edit</h1>
    <hr />
    <div class="form-group">
        <label asp-for="Heading"></label>
        <input asp-for="Heading" class="form-control" />
        <span asp-validation-for="Heading" class="text-danger"></span>
    </div>
    <p>Image</p>
    <p>(leave blank if you don't want to change the picture)</p>
    <div class="custom-file">
        <input asp-for="ImageUpload" class="custom-file-input">
        <label asp-for="ImageUpload" class="custom-file-label">Choose image...</label>
        <span asp-validation-for="ImageUpload" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <input asp-for="Id" hidden>

    <a class="btn btn-danger float-left" asp-area="Fitness" asp-controller="Exercises" asp-action="Details" asp-route-exerciseId="@Model.ExerciseId">Cancel</a>
    <button type="submit" class="btn btn-success float-right">Edit</button>
</form>

@section Scripts{
    <script type="text/javascript">changeFileInputLabel();</script>
}